# Generated by Django 5.0.1 on 2024-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
